sudo: required

dist: xenial

language: go

services:
  - docker

go:
  - 1.12.1

env:
  - GO111MODULE=on DOCKER_CLI_EXPERIMENTAL=enabled

install: true

script:
  - make
  - make unit
  - make lint
  - make container

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - make manifest && make manifest-latest
